[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "jinja"
file-types = ["j2"]
language-servers = ["tailwindcss-ls", "vscode-html-language-server"]

[[language]]
name = "tera"
file-types = ["tera"]
language-servers = ["tailwindcss-ls", "vscode-html-language-server"]


[[language]]
name = "tsx"
shebangs = ["node"]
roots = ["tsconfig.json", "package.json"]
file-types = ["tsx"]
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["ty", "helix-assist"]
auto-format = true

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "scheme"
file-types = ["scm"]
language-servers = ["steel", "helix-assist"]
formatter = { command = "schemat" }
auto-format = true

[language-server.steel]
command = "steel-language-server"

[language-server.helix-assist]
command = "helix-assist"
args = ["--handler", "gemini", "--num-suggestions", "2"]
